### ISSUE TITLE
Foreign tables filtering issue

### ISSUE THREAD

**Issue by tbrains** [supabase-community/postgrest-py#123]
When filtering on a foreign table column, the function sanitize_param adds extra quotes if the param has restricted characters, this breaks and throws an error.

'foreign_table.col1' -> sanitize_param -> '"foreign_table.col1"'

I checked, by removing the extra quotes, the filter works as expected. sanitize_param is used twice => filter() and in_().

What do you suggest?

**Comment by anand2312** [comment]
Duplicate of supabase-community/supabase-py#203 ; we'll get to fixing this soon. Thanks for the report!

**Comment by J0** [comment]
Closing in favour of tracking on #189
