### ISSUE TITLE
how can i update column use another column or use function such as now()

### ISSUE THREAD

**Issue by rmGFW** [supabase-community/postgrest-py#144]
i want update update_time to now() 
```python
client.from_("some_table").update({"update_time":"now()"}). ....
```

**Comment by anand2312** [comment]
You could probably just get the current time client-side with `datetime.now().isoformat()` and pass that in here; but more broadly if you want to run some postgres functions you'd have to write an SQL function, and call that SQL function with `[Client.rpc](https://postgrest-py.readthedocs.io/en/latest/api/client.html#postgrest.AsyncPostgrestClient.rpc)` method.
