### ISSUE TITLE
Unable to match

### ISSUE THREAD

**Issue by A-Y-U-S-H-Y-A** [supabase-community/postgrest-py#178]
**Describe the bug**
Unable to run the match command after select

**To Reproduce**
email = urllib.parse.quote("ayubhai1234@gmail.com", safe='')
rec.table('data').select('*').match({'email': email}).execute()

**Output**
postgrest.exceptions.APIError: {'code': 'PGRST104', 'details': 'Failed to parse [("email","Filters.EQ.ayubhai1234%40gmail.com")]', 'hint': None, 'message': 'Unexpected param or filter missing operator'}

**Desktop (please complete the following information):**
 - OS: Win 10

**Comment by J0** [comment]
This seems to work fine for me too 
<img width="852" alt="CleanShot 2023-01-23 at 10 22 33@2x" src="https://user-images.githubusercontent.com/8011761/213955901-e3a0894f-4ec9-4d2f-85bb-093a82b03549.png">


Could you please confirm the `postgrest-py` version that you are using?

**Comment by J0** [comment]
Closing for now but feel free to re-open if issue persists
