### ISSUE TITLE
Unable to update

### ISSUE THREAD

**Issue by A-Y-U-S-H-Y-A** [supabase-community/postgrest-py#179]
**Describe the bug**
Unable to update

**To Reproduce**
rec.table('data').update({"cookie":cookie, "qrdata":qrdata, "otptime":'2023-01-08 13:21:52.676377'}).filter('email',"eq",email).execute()

**Expected behavior**
Update without error

**Output**
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Additional info**
The update takes place, but the error is thrown

**Comment by J0** [comment]
`filter` is a keyword in Python so I think the operation might not be performing what you expect it to be doing. Could you instead try using `.eq`? 

`rec.table('data').update({"cookie":cookie, "qrdata":qrdata, "otptime":'2023-01-08 13:21:52.676377'}).eq('email', email).execute()`

Seems to work fine on my end. Going to close for now but let me know if there are further issues

<img width="840" alt="CleanShot 2023-01-23 at 10 10 52@2x" src="https://user-images.githubusercontent.com/8011761/213955043-f422ac50-de80-4ed5-9e0d-3a86f418b72d.png">

**Comment by J0** [comment]
Filter case seems to work fine on my end too - could you check that the input fields have valid types?
<img width="879" alt="CleanShot 2023-01-23 at 10 16 02@2x" src="https://user-images.githubusercontent.com/8011761/213955499-94ea2154-399a-45ca-a8aa-3853495d326b.png">

**Comment by J0** [comment]
Closing for now but feel free to re-open if issue persists
