### ISSUE TITLE
Typings disagree with bulk insert/upsert APIs

### ISSUE THREAD

**Issue by evanandrewrose** [supabase-community/postgrest-py#182]
https://github.com/supabase-community/postgrest-py/blob/4afd352cfa16e5d5288f0678275996bd1422e3eb/postgrest/_sync/request_builder.py#L232

I believe the `json` parameter here should be of type `Union[dict, list]`, to indicate bulk update capability. I tested bulk updates and they do work, but my IDE complains.

Relevant supabase api docs: https://supabase.com/docs/reference/javascript/insert (choose the "Bulk create" tab)

**Comment by J0** [comment]
Thanks for the catch!  Opened a PR
