### ISSUE TITLE
sanitize_param() not correctly resolving when using nested columns

### ISSUE THREAD

**Issue by Vidski** [supabase-community/postgrest-py#189]
**Describe the bug**
When filtering for a nested column, sanitize_param is adding unneccessary " "

**To Reproduce**
`supabase.table('character_inventory').select('character(*), slot, item(*, template(*))').eq('character.user_id', user_id).execute()`

resolves to:
`/rest/v1/character_inventory?select=character(*),+slot,+item(*,+template(*))&"character.user_id"=eq.2731f9cc-17f4-42a2-839a-d25dfe8d90a8` returns HTTP 400

**Expected behavior**
Should resolve to:
`/rest/v1/character_inventory?select=character(*),+slot,+item(*,+template(*))&character.user_id=eq.2731f9cc-17f4-42a2-839a-d25dfe8d90a8` returns HTTP 200

**Screenshots**
![image](https://user-images.githubusercontent.com/36316706/166309069-a07390a7-c1c8-4aa1-9d54-c6fbcf5234d5.png)
![image](https://user-images.githubusercontent.com/36316706/166309653-3d50370a-1b26-49ac-8325-f421665ddeba.png)

**Desktop:**
 - OS: Windows 11
 - Version: latest

**Comment by anand2312** [comment]
Fixed by #222
