### ISSUE TITLE
Interpreting spaces as table names in foreign table queries

### ISSUE THREAD

**Issue by dreinon** [supabase-community/postgrest-py#19]
Found the problem!
It's how python client is interpreting the query. I noticed table name `precios` had a space after it in the error message:
```json
{
  "hint": "If a new foreign key between these entities was created in the database, try reloading the schema cache.",
  "message": "Could not find a relationship between alumnos_matriculas and precios  in the schema cache"
}
```

Then, I found out the query my code was the following:
```python
db.table('alumnos_matriculas') .select('mat_id, precios (*)').execute()
```

And when I removed the space between table_name `precios` and `(*)` got it working:
```python
db.table('alumnos_matriculas') .select('mat_id, precios(*)').execute()
```

_Originally posted by @dreinon in https://github.com/supabase/supabase/discussions/3186#discussioncomment-1320085_

**Comment by bariqhibat** [comment]
For this issue, can we just `.strip()` the column names? @dreinon

**Comment by anand2312** [comment]
@bariqhibat strip would only remove the spaces at either ends of the string, but here we need the space from in between to be removed. I wonder if we could get away with just removing spaces from the string entirely. If that doesn't work, I think it'd be too much effort to selectively only remove spaces in this case, and just document this somewhere.

**Comment by steve-chavez** [comment]
Just wanted to mention that this is something that we're addressing in PostgREST itself. We parse whitespace in our syntax. For example for the `and`/`or` operators:

```http
GET /entities?and=( and ( id.in.( 1, 2, 3 ) , id.eq.3 ) , or ( id.eq.2 , id.eq.3 ) )&select=id
```

(Taken from this test [here](https://github.com/PostgREST/postgrest/blob/31b3db1cec0226025f61bf6dfb8b901b2a0e8512/test/spec/Feature/Query/AndOrParamsSpec.hs#L195-L197))

For this case, we misssed applying our [lexeme parser](https://github.com/PostgREST/postgrest/blob/31b3db1cec0226025f61bf6dfb8b901b2a0e8512/src/PostgREST/Request/QueryParams.hs#L290-L294) for the embedding target(`precios`)  

Once this is solved, OP's issue won't give an error anymore.

**Comment by anand2312** [comment]
Thanks @steve-chavez ! That definitely saves us some trouble here 😄

**Comment by laurenceisla** [comment]
We've been checking with @steve-chavez and it turned out not to be a simple fix and may need a bigger refactor to allow this. The error message was improved for embedding, so it could be a help to identify this issue for now. For instance, in this case the new error message would be:

```json
"message": "Could not find a relationship between 'alumnos_matriculas' and 'precios ' in the schema cache"
```

**Comment by anand2312** [comment]
@laurenceisla Do you think removing all spaces here (on the client) would be a viable workaround?

**Comment by steve-chavez** [comment]
> Do you think removing all spaces here (on the client) 

@anand2312 Keep in mind that a table name with spaces(like `CREATE TABLE "this is my table  "`) is a valid identifier, so not all spaces should be removed.

Also, as I recall it, the main cause of confusion(for me as well) on https://github.com/supabase/supabase/discussions/3186#discussioncomment-1320085 was that the error message did not make clear that there was whitespace on the foreign table name. The new error message that laurenceisla mentioned should already solve that.

You might consider just closing the issue and perhaps documenting the limitation.

**Comment by steve-chavez** [comment]
> Do you think removing all spaces here (on the client) would be a viable workaround until it is fixed at postgrest?

@anand2312 Sorry. I've just noted that [postgrest-js does remove whitespaces](https://github.com/supabase/postgrest-js/blob/master/src/lib/PostgrestTransformBuilder.ts#L13-L30) and it has been working good, so it could be a good idea to do the same for `postgrest-py`.
