### ISSUE TITLE
eq adding Filters.EQ istead of eq

### ISSUE THREAD

**Issue by anoninthekop** [supabase-community/postgrest-py#190]
**Describe the bug**
On python 3.11 using eq is adding `column_name=Filters.EQ` to the query string instead of` column_name=eq` causing the error postgrest.exceptions.APIError: {'code': 'PGRST104', 'details': 'Failed to parse [("column_name","Filters.EQ.1")]', 'hint': None, 'message':
 'Unexpected param or filter missing operator'}

**To Reproduce**
1. `supabase.table("table1").select("column1").eq("column2", 1).order("id",  desc=True ).limit(1).single().execute()`
2. resulting query is `database/table1?select=column1&column2=Filters.EQ.1&order=id.desc&limit=1 | python-httpx/0.23.0`
3. See error postgrest.exceptions.APIError: {'code': 'PGRST104', 'details': 'Failed to parse [("column2","Filters.EQ.1")]', 'hint': None, 'message':
 'Unexpected param or filter missing operator'}

**Expected behavior**
query should should be `database/table1?select=column1&column2=eq.1&order=id.desc&limit=1 | python-httpx/0.23.0`

**Comment by J0** [comment]
Hey! 

Just tested @espinozajp 's query with Python3.11 and it seems to work - going to close now but  feel free to report back if there are issues.

Thanks!
