### ISSUE TITLE
How to perform Full-text Search?

### ISSUE THREAD

**Issue by yuchdev** [supabase-community/postgrest-py#191]
You see, I tried to execute `select().textSearch()`, which is [provided](https://supabase.com/docs/guides/database/full-text-search) by JS API, but it sems to not ported to the PythonAPI

Executing the same request as a raw SQL query to Postgres would've solved the problem, but I didn't find it either.
Could you give some guidance, on how such a functionality could be performed through your API?
Sorry if the questions are too basic, I just started to use it.

**Comment by J0** [comment]
Let's port this over! Here's the [JS source](https://github.com/supabase/postgrest-js/blob/860387eddf35224543ccb0f7ccdd5c056792bb35/src/PostgrestFilterBuilder.ts#L331) if anyone wants to take up the issue. Else I'll get to it when a slot frees up

**Comment by J0** [comment]
Hey we just ported a utility `text_search` command over, going to close for now - feel free to give it a try -
the usage looks something like: `client.from_("listing").select("*").text_search("description", f"'{query}'", {"type": "websearch", "config": "english"}).execute()`

Going to close this issue for now but feel free to let me know if there are still issues

Thanks!
