### ISSUE TITLE
How to use OR in filters (match at least one filter)?

### ISSUE THREAD

**Issue by arinmirza** [supabase-community/postgrest-py#196]
I'm trying to write a simple OR query as in the [javascript documentation](https://supabase.com/docs/reference/javascript/or).

```js
const { data, error } = await supabase
  .from('countries')
  .select('name')
  .or('id.eq.2,name.eq.Algeria')
```

The `.or` operator seems not to be ported to Python and I could not find a workaround for this. Can you help me with this?

**Comment by TonsiTT** [comment]
Any progress on this?

**Comment by J0** [comment]
Hey @TonsiTT just seeing this.

Yeah we're looking into this - let's track this on #137. Going to close this for now- hope that's okay.

Thanks!
