### ISSUE TITLE
How can I reproduce a not in query in Python?

### ISSUE THREAD

**Issue by mohnish7** [supabase-community/postgrest-py#198]
**Describe the bug**
Using the javascript library, it's very easy to do a `not('columnName', 'in', '(values)')` to perform a `not in` query, however, I haven't been able to do so using the python client. I know that we can perform an `in` query using `in_`, but I would love to be able to perform a `not in` query too so that our users can query more easily

**Comment by J0** [comment]
Hey @mohnish7,

Hope the suggestion above resolved your issue - going to close this for now but feel free to re-open or reach back out if there are still issues or doubts.

Thanks!
