### ISSUE TITLE
Update/improve docs

### ISSUE THREAD

**Issue by guillego** [supabase-community/postgrest-py#199]
# Improve documentation

[Docs](https://postgrest-py.readthedocs.io/en/latest/) are a bit outdated and lacking in examples

## Describe the problem
When I started using the library I missed a bit more of a comprehensive set of examples, getting started, etc. And had to go back and forth between the docs, the code and the supabase docs for the js client.

## Describe the improvement

- Add a "getting started" section. Like a basic set of snippets of code to start the client, connect it to a postgrest server, give an example of how to do this with the supabase server and do some basic queries.
- Add more examples: more complex queries with filters and modifiers, bulk updates, etc.

## Additional context

I'm happy to contribute and improve these docs! Let me know where I can start (it's my first time contributing to an open source project).

**Comment by J0** [comment]
Hey @guillego 

Thank you so much for offering to improve the docs! It definitely needs some love. In terms of the lib there are two main places where one could start

1. The documentation within the site
2. The Postgrest section on the [Supabase Python ref docs](https://supabase.com/docs/reference/python/select) on the website which has much higher visibility 

For 2, you can see [the main thread](https://github.com/supabase-community/supabase-py/issues/36) for details

For 1, we use Sphinx and most of the docs are [within this folder ](https://github.com/supabase-community/postgrest-py/tree/master/docs)

Feel free to let me know if there are any queries/doubts

**Comment by guillego** [comment]
Hey Joel @J0!
Finally had some time to improve the official [Supabase ref docs](https://github.com/supabase/supabase/pull/12532).

Cheers!

**Comment by J0** [comment]
Thanks so much @guillego! Appreciate it
