### ISSUE TITLE
RPC call expects `data` in APIResponse to be a list, which is not mandatory

### ISSUE THREAD

**Issue by timreibe** [supabase-community/postgrest-py#200]
# Bug report

## Describe the bug

The response of an RPC query expects `data` as `List[Dict[str, Any]]` in the `APIResponse` object found in `postgrest/base_request_builder.py`, but it must not be a list.

This call worked in version `0.10.3`, but does not in version `0.10.4`

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Install this function in the PostgreSQL database ([from here](https://github.com/supabase-community/supabase-custom-claims)) to get the user's `raw_app_meta_data` from the Supabase user object:

```sql
CREATE OR REPLACE FUNCTION get_claims(uid uuid) RETURNS "jsonb"
    LANGUAGE "plpgsql" SECURITY DEFINER SET search_path = public
    AS $$
    DECLARE retval jsonb;
    BEGIN
      IF NOT is_claims_admin() THEN
          RETURN '{"error":"access denied"}'::jsonb;
      ELSE
        select raw_app_meta_data from auth.users into retval where id = uid::uuid;
        return retval;
      END IF;
    END;
$$;
```
3. Make the respective RPC call with an authorized Supabase client

```python
sb.rpc(
        fn="get_claims",
        params={"uid": str(user_id)}
    ).execute()
```

## Expected behavior

I expect to receive the response body _as is_. 

## System information

- OS: macOs
- Version of postgrest-py: 0.10.4

## Additional context

Thrown error: 

```shell
Traceback (most recent call last):
  File "/Users/timreibe/VENV/supabase-stripe-webhook/lib/python3.9/site-packages/postgrest/_sync/request_builder.py", line 65, in execute
    return APIResponse.from_http_request_response(r)
  File "/Users/timreibe/VENV/supabase-stripe-webhook/lib/python3.9/site-packages/postgrest/base_request_builder.py", line 157, in from_http_request_response
    return cls(data=data, count=count)
  File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for APIResponse
data
  value is not a valid list (type=type_error.list)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/timreibe/Documents/Code/py/supabase-stripe-webhook/app.py", line 29, in <module>
    user_id = _get_custom_claims("f25f0ca7-4116-4587-a445-084057d52b50")
  File "/Users/timreibe/Documents/Code/py/supabase-stripe-webhook/src/sb/custom_claims.py", line 64, in _get_custom_claims
    print(res.execute())
  File "/Users/timreibe/VENV/supabase-stripe-webhook/lib/python3.9/site-packages/postgrest/_sync/request_builder.py", line 69, in execute
    raise APIError(r.json()) from e
postgrest.exceptions.APIError: {'scid': 'STRIPE_USER_ID', 'provider': 'email', 'providers': ['email']}
```

**Comment by J0** [comment]
Hey @timreibe,

Thanks for the detailed replication instructions - it was helpful in understanding the issue. I'm planning to make the validator allow for both `List[Dict[str, any]] | Dict[str, any]` .

Let me know if you have any thoughts or concerns about this fix.

Thanks!
Jo

**Comment by TonsiTT** [comment]
Having the same issue

**Comment by chrisgoddard** [comment]
Any update on this issue? It's a pretty big blocker in not being able to use this library (or the supabase python client)

**Comment by ShantanuNair** [comment]
So are RPC calls at the moment largely broken on supabase-py/postgrest-py? @kiwicopple

**Comment by ShantanuNair** [comment]
Related? https://github.com/supabase-community/supabase-py/issues/405 and https://github.com/supabase-community/supabase-py/issues/470
