### ISSUE TITLE
eq does not work when your field name is "apikey"

### ISSUE THREAD

**Issue by Akiren** [supabase-community/postgrest-py#203]
If your table has a field called "apikey" queries will always be truthy regardless of if they really are

data = supabase.table('users').select('email, api_key').eq('api_key', 'fakekey').execute().dict()

data will always return data... Found the javascript issue after 2.5 hours of questioning the nature of reality.

This bug existed and was fixed in the javascript version of supabase
https://github.com/supabase/supabase/issues/5465

**Comment by J0** [comment]
Closing, please prefix your key as `user_apikey` instead..
