### ISSUE TITLE
How do i insert multiple rows with only one write?

### ISSUE THREAD

**Issue by dj-fiorex** [supabase-community/postgrest-py#204]
**Describe the bug**
Hello, i need to know if there is a way to insert multiple rows with a single write. It'ss a feature that i think is a must to work with an hosted version of supabase and to lower costs of writing to db.

Right now supabase client insert
`supabase.table("table_name").insert(data).execute()`
support only a dict and not a list[dict]

I'm a developer so i could do something if someone point me to the right direction.

Thanks

**Comment by silentworks** [comment]
@anand2312  do we need an `insert_many` in this instance since the normal `postgres-js` only have a single `insert` methods that takes a dict or a list?

**Comment by anand2312** [comment]
Sorry @silentworks didn't see this earlier. I don't think we need it separately.
