### ISSUE TITLE
update with no content crush (via supabase)

### ISSUE THREAD

**Issue by rotemCyberillium** [supabase-community/postgrest-py#206]
# Bug report

## Describe the bug

in https://github.com/supabase-community/postgrest-py/blame/0fa4e4eeaa76dd7575b75d36ec7a04c04b4c0917/postgrest/_sync/request_builder.py#L63

we can see a check added for `200 <= r.status_code <= 299`

but in update request(via supabase python client) 
                request = controller.supabase_table.update({"param": "test1"}).eq('param', "test2")

if there are no rows with param=test2, the response is 404 not found

## To Reproduce

request = controller.supabase_table.update({"param": "test1"}).eq('param', "test2")
with no rows with param=test2

## Screenshot

![image](https://user-images.githubusercontent.com/110523032/215783074-9b60f5a0-0509-49e1-b722-78934f3a6470.png)

and somehow it crashes with `AttributeError: 'list' object has no attribute 'get'` so it was hard to debug the problem

## Expected behavior

don't crash

**Comment by J0** [comment]
Hey just looking at this,

I think the workaround here might be to check in the `APIError` if the status is 404 and the list is empty `[]`. If so we can probably return the error message directly - this should also account for any other 404 cases.

**Comment by J0** [comment]
Hey ,

Put in a fix - feel free to try again and let me know if there are still issues
