### ISSUE TITLE
AttributeError: 'list' object has no attribute 'json'

### ISSUE THREAD

**Issue by sureshdsk** [supabase-community/postgrest-py#21]
Run sample code from readme.md
```python
import asyncio
from postgrest_py import PostgrestClient

async def main():
    async with PostgrestClient("http://localhost:3000") as client:
        r = await client.from_("countries").select("*").execute()
        countries = r.json()

asyncio.run(main())
```

` countries = r.json() ` raises below error
```
AttributeError: 'list' object has no attribute 'json'
```

Seems execute method already returns a json.

**Comment by dreinon** [comment]
Hi, the `execute` method returns a list of dictionaries that represent each row from the query. If you are sure your query only returns 1 row, you can use `single()` method before `execute`, but take into account this method will return an error if there are no results or more than one results in the query. If you are not sure you are always going to get 1 row, I would use `execute` and then get the first index of that list.

To turn it into a json, you may use `json.dumps(result_obtained_from_execute)` having imported `json` before (it's in the python standard library).

**Comment by sureshdsk** [comment]
should we update the documentation with your explanation?  The examples mentioned with `.json()` in the readme file doesn't work.

**Comment by dreinon** [comment]
Hi! Closing this issue since it should be solved in the current version. Thanks for reporting :slightly_smiling_face: !
