### ISSUE TITLE
Release latest version to pypi

### ISSUE THREAD

**Issue by timkpaine** [supabase-community/postgrest-py#226]
Looks like supabase has minimum version `0.10.6` https://github.com/supabase-community/supabase-py/blob/develop/pyproject.toml#L19

But latest pypi version is still at `0.10.4`

This blocks (among other things) the `conda-forge` build of supabase until `postgrest` can work its way through, mind publishing these to pypi when you get a chance?
https://github.com/conda-forge/supabase-feedstock/pull/4

**Comment by J0** [comment]
hmm strange. Let me publish it now

**Comment by J0** [comment]
Hmm it seems to be at `0.10.6` on my end. Perhaps it depends on postgrest-py? I can publish to there as well but we should eventually look into deprecating that namespace.

<img width="465" alt="CleanShot 2023-02-27 at 08 27 38@2x" src="https://user-images.githubusercontent.com/8011761/221447019-6a375c6e-bbc4-40ce-bfc0-95e3cdb24026.png">

**Comment by J0** [comment]
published on  `postgrest-py` as well

<img width="597" alt="CleanShot 2023-02-27 at 08 31 22@2x" src="https://user-images.githubusercontent.com/8011761/221447205-a7063291-ae26-4a99-9df6-b3d8e1d37eea.png">

Lmk if there are still issues

**Comment by timkpaine** [comment]
ah that's probably it, did you recently take over `postgrest` or something? I will need to remap the conda package for it https://github.com/conda-forge/postgrest-feedstock/blob/main/recipe/meta.yaml#L2

**Comment by timkpaine** [comment]
<img width="347" alt="Screenshot 2023-02-26 at 22 02 48" src="https://user-images.githubusercontent.com/3105306/221463254-bc3f7efa-0bfa-4418-af0e-d6056375d80e.png">
ah yep cool, conda wouldn't have auto-ticked postgrest-py but I'll move it over to that now

**Comment by timkpaine** [comment]
https://github.com/conda-forge/postgrest-feedstock/pull/2

**Comment by J0** [comment]
@timkpaine Yup! We did, sorry for the lack of update and thanks for keeping the ball rolling w.r.t Conda packages. Really appreciate it!
