### ISSUE TITLE
Count feature

### ISSUE THREAD

**Issue by sureshdsk** [supabase-community/postgrest-py#25]
I'm working on implementing count feature.  I would like to check with the signature below. I'm trying to keep it similar to js client signature.  

 # To get count along with records
```python
countries, count = await client.from_("countries").select("id", "name", count="exact").eq("continent", "Asia").execute()
print(countries, count)
```

 # To get only count
```python
asia_total = await client.from_("countries").select("*" , count="exact", head=True).eq("continent", "Asia").execute()
print(asia_total)
```

**Comment by lqmanh** [comment]
I'll have a look this weekend.

**Comment by sureshdsk** [comment]
@lqmanh were you able to check this?

**Comment by lqmanh** [comment]
@sureshdsk PR #26 was merged into master, you can try it now. However, it created a backward-compatibility issue and I need to bump postgrest-py to v1, and it may take some time.

I'll close this issue now. If you have any problems, feel free to open other ones.
