### ISSUE TITLE
pydantic > 2.1.1 is too restrictive

### ISSUE THREAD

**Issue by olirice** [supabase-community/postgrest-py#282]
# Restrictive Dependency
Last week `pydantic`'s minimum version was bumped from `1.9` to `2.1.0`, which was released less than 3 weeks ago.
https://github.com/supabase-community/postgrest-py/commit/85ff4063d25ae859155fa42a152268c6cc138deb

`pydantic` is a common dependency, particularly among API building libraries and this makes `postgrest-py` (and upstream projects like supabase-py) incompatible with those libs

For example, we are currently incompatible with FastAPI and LangChain

**Comment by rexwangcc** [comment]
Would it be possible to have this fix in a released version? We have run into this issue in several different scenarios and the most recent one is like:

```
Because no versions of supabase match >1.0.4,<2.0.0
 and supabase (1.0.4) depends on postgrest (>=0.10.8,<0.11.0), supabase (>=1.0.4,<2.0.0) requires postgrest (>=0.10.8,<0.11.0).
Because postgrest (0.10.8) depends on pydantic (>=2.1.0,<3.0)
 and no versions of postgrest match >0.10.8,<0.11.0, postgrest (>=0.10.8,<0.11.0) requires pydantic (>=2.1.0,<3.0).
Thus, supabase (>=1.0.4,<2.0.0) requires pydantic (>=2.1.0,<3.0).
So, because FUSS depends on both pydantic (^1.10.9) and supabase (^1.0.4), version solving failed.
```

Thanks!
