### ISSUE TITLE
PGRST104 error on deployment

### ISSUE THREAD

**Issue by asontha** [supabase-community/postgrest-py#306]
**Describe the bug**
Seems to be working locally but when I deploy to fly.io using heroku container, running into the following error:
```
postgrest.exceptions.APIError: {'code': 'PGRST104', 'details': 'Failed to parse [("channel_id","Filters.EQ.<CHANNEL ID>")]', 'hint': None, 'message': 'Unexpected param or filter missing operator'}
```

this is the query I'm running:
```
namespace_query = supabase.table("channel-configuration").select("*").eq("channel_id", channel_id).execute()
```

Again this query is running fine locally.

**Expected behavior**
Runs query normally against DB table and returns the expected result.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS 12.5

**Comment by silentworks** [comment]
I haven't been able to replicate this on the latest version of the library so closing this out as fixed.
