### ISSUE TITLE
URI too long for large filter predicates

### ISSUE THREAD

**Issue by trevor-e** [supabase-community/postgrest-py#365]
# Bug report

## Describe the bug

This is essentially the same issue as https://github.com/supabase/postgrest-js/issues/393 in the Javascript library.

Large filter predicates fail because the resulting GET request URI is too long.

## To Reproduce

Create a sufficiently large filter and observe that it fails:
```
# comment_ids was a couple hundred items in my case
self.supabase.table('some_table').select('id, comment_id').in_('comment_id', comment_ids).execute()
```
throws an error:
```
File "/usr/local/lib/python3.11/site-packages/postgrest/_sync/request_builder.py", line 74, in execute raise APIError(generate_default_error_message(r)) postgrest.exceptions.APIError: {'message': 'JSON could not be generated', 'code': 414, 'hint': 'Refer to full message for details', 'details': "b'URI too long\\n'"
```

## Expected behavior

postgrest should be able to handle these cases, the filter I'm building is not that much data. I don't know much about the internals but it looks like it's building a GET request with query params, can it not perform a POST request with a body instead? If that's not possible, can the library perform some automatic chunking under the hood? 

## System information

- Python 3.11
- Linux
- supabase==2.3.0
- postgrest==0.13.0

## Additional context

I saw the similar tickets opened for the other client repos but figured I'd open this for any Python users that stumble across it. A bit confused if this is library specific or not.

**Comment by anand2312** [comment]
This isn't library specific. Until PostgREST changes the way it accepts queries I don't think we can do anything on the client-side, the issue you've linked suggests using an RPC function

**Comment by silentworks** [comment]
I agree with @anand2312 on this one, its not an issue with this library itself. As suggested you should be using a RPC function instead.
