### ISSUE TITLE
Use inheritance to improve our code base

### ISSUE THREAD

**Issue by dreinon** [supabase-community/postgrest-py#40]
As @lqmanh mentioned [here](https://github.com/supabase-community/postgrest-py/pull/30#issuecomment-959742469), inheritance is the way to go but #30 was already too big to include.

Therefore, we should open a PR refactoring the lib using inheritance.

**Comment by dreinon** [comment]
@leynier are you able to work on this? Might be interesing since you already had work done related to this issue.

**Comment by leynier** [comment]
Yeah, assign me to the issue 👌👍
