### ISSUE TITLE
Error: QueryParams are immutable when using order.

### ISSUE THREAD

**Issue by tbrains** [supabase-community/postgrest-py#43]
Get the following error when using order

> QueryParams are immutable since 0.18.0. Use `q = q.set(key, value)` to create an updated copy.

Ex: `data = supabase.table('TABLE_NAME').select('*').order("id")`

Possible Fix (below): Update order function in class SelectRequestBuilder in request_builder.py

```
    def order(self, column: str, *, desc=False, nullsfirst=False):
        self.session.params = self.session.params.add("order", f"{column}{'.desc' if desc else ''}{'.nullsfirst' if nullsfirst else ''}")
        return self
```

**Comment by alif-arrizqy** [comment]
hello..
what query is used to perform filter order() ?
