### ISSUE TITLE
The error message: 'Error in $: not enough input' does not provide any hints on what is actually wrong. 

### ISSUE THREAD

**Issue by Vad1mo** [supabase-community/postgrest-py#7]
# Bug report

## Describe the bug

after inserting the following values into the table:

```python
instance_id  # None
organization_guid # value
plan_id # value
active # value
order_date # None, but is set on insert
updated_at # update trigger from extension
```

![image](https://user-images.githubusercontent.com/1492007/117583619-71152d00-b108-11eb-9bbe-a58d3a3c6e19.png)

I want to set the active flag to `true` by creating an update, but it fails with this error message:  `'Error in $: not enough input'`

```python

order_book = OrderBook(instance_id=instance_id, organization_guid=organization_guid, plan_id=details.plan_id,
                               active=False)
        response = supabase.table("instance").insert(order_book).execute() # works
        
order_book['active'] = True
response: OrderBook = supabase.from_("instance").update(order_book).eq(
    'id', f"{order_book['id']}").execute()        # fails with - Error in $: not enough input
         
```
I tried also with only  `active = true` like below, but it didn't work eighter.
`supabase.from_("instance").update({'active': 'true'}).eq(
            'id', f"{order_book['id']}").execute()`
            
Its not clear to me what is actually wrong or what is missing or how to properly debug the query.

**Comment by 99cv** [comment]
Hi, 
is there any recommendation how to handle this. I got the same response and really don't have any clue what's wrong. Even if I change the parameters I get the same response.

**Comment by keosariel** [comment]
Can you guys kindly send a `traceback`? It'll be helpful

**Comment by prescience-data** [comment]
Started receiving this as well when sending a direct request from Postman

**Comment by dreinon** [comment]
I have the same problem when trying to update

**Comment by dreinon** [comment]
UPDATE: Working if I install locally `develop` branch. It seems it was fixed by [this PR](https://github.com/supabase-community/supabase-py/pull/41) but it either hasn't been merged to master or it's the fact that there hasn't been a release since April. Nevertheless, I'm sure the great work @J0 and the other contributors are doing will lead to a release sooner than later!

**Comment by bolt-mechaverse** [comment]
I confirm, the shared PR from @dreinon fixes the issue.

**Comment by dreinon** [comment]
Closing since this is already solved 🙂
