### ISSUE TITLE
PyPI permissions for Maintainers

### ISSUE THREAD

**Issue by J0** [supabase-community/postgrest-py#78]
Hey @lqmanh,

Sorry to bother you again.  I wasn't too sure how to best reach you so I thought I'd open an issue here -- by any chance could you also add @leynier as a maintainer to the postgrest-py when you get the time? 
Thanks!

Assigning Leynier and dreinon just to let them know!

Joel

**Comment by lqmanh** [comment]
Already done.
@leynier Have you received the invitation?

**Comment by leynier** [comment]
> Already done.
> @leynier Have you received the invitation?

Yes, thank you very much.

**Comment by J0** [comment]
Thanks @lqmanh !
