### ISSUE TITLE
"Order" modifier doesn't seem to work

### ISSUE THREAD

**Issue by iceanfire** [supabase-community/postgrest-py#80]
# Bug report

## Describe the bug
When I set an "order" modifier via the python api, results are not ordered as requested. When I then look at the logs, the order request doesn't seem to have been sent to the server.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. Add "order" modifier to your query  (example: data = supabase.table("brokerData").select("price").order("price").limit(111).execute())
2. Run Query
3. Notice results are not ordered

## Expected behavior
Returned results should be ordered by the requested column.

## System information

- OS: Mac
- IDE: Replit
- Language: Python

**Comment by leynier** [comment]
Fixed in [postgrest-py: v0.8.1](https://github.com/supabase-community/postgrest-py/releases/tag/v0.8.1) and [supabase-py: v0.3.2](https://github.com/supabase-community/supabase-py/releases/tag/v0.3.2)

**Comment by J0** [comment]
> > I think that be useful a param for setting debug mode in `postgrest-py` to see the structure of the request at the end. I think that with that feature, bug fixing will be easier.
> 
> @supabase-community/python-maintainers

Thanks @leynier! Opened an issue for this is #81
