### ISSUE TITLE
Add debug parameter to see final shape of query

### ISSUE THREAD

**Issue by J0** [supabase-community/postgrest-py#81]
As discussed in #80, it might be useful for us to add a debug flag which will allow us to view the structure of the request at the end.

This will allow us to better debug issues/queries that arise.

**Comment by anand2312** [comment]
The user can just set the log level to DEBUG, httpx does debug level logs for every request.

```py
from logging import basicConfig, DEBUG
from postgrest_py import SyncPostgrestClient

basicConfig(level=DEBUG)

client  = SyncPostgrestClient(...)

client.from_("test").select("*").eq("email", "b.com").execute()
client.from_("test").select("*").eq("names", "Hibro").eq("roll_numbers", "21312").execute()
```
gives the following output
```
DEBUG:httpx._client:HTTP Request: GET https://<URL>/rest/v1/test?select=%2A&email=eq.%22b.com%22 "HTTP/1.1 200 OK"
DEBUG:httpx._client:HTTP Request: GET https://<URL>/rest/v1/test?select=%2A&names=eq.Hibro&roll_numbers=eq.21312 "HTTP/1.1 200 OK"
```
I think this is good enough (maybe we could log headers sent as well), maybe add a note about this in documentation (when we get around to it). What do you think? @J0 @dreinon

**Comment by J0** [comment]
httpx with debug sounds good to me

Thanks for the explanation!

**Comment by dreinon** [comment]
I find it great!
