### ISSUE TITLE
Implemement maybeSingle method

### ISSUE THREAD

**Issue by dreinon** [supabase-community/postgrest-py#94]
[JS Implementation](https://github.com/supabase/postgrest-js/blob/aa223b4569b5c08714bb1d029e8f780e19db2b09/src/lib/PostgrestTransformBuilder.ts#L110)

**Comment by bariqhibat** [comment]
Hey @dreinon, can I work on this?

**Comment by anand2312** [comment]
How is the maybe_single method different from `single`?

**Comment by dreinon** [comment]
> How is the maybe_single method different from `single`?

The `single` method raises an error if the db response record count is different from 1 (if it doesn't find any records, it would raise an error). The `maybeSingle` method raises an error only if the db response record count is greater than 1, being 0 and 1 records valid.

**Comment by anand2312** [comment]
Thanks for the explanation! 😄
